.\" Manpage for openkylinmenueditor-menu-validate.
.TH openkylinmenueditor-menu-validate "1" "January 2018" "openkylinmenueditor 2.1" "openkylinmenueditor-menu-validate man page"
.SH NAME
openkylinmenueditor-menu-validate \- display GMenu debug output
.SH SYNOPSIS
openkylinmenueditor-menu-validate
.SH DESCRIPTION
openkylinmenueditor-menu-validate is intended as a convenient way to access 
GMenu's debugging output on stderr, which exposes information about 
invalid desktop files, without doing strange hacks on openkylinmenueditor's own 
stderr
.SH OPTIONS
openkylinmenueditor-menu-validate does not take any options.
.SH SEE ALSO
openkylinmenueditor(1)
.SH BUGS
No known bugs.
.SH AUTHOR
OmegaPhil (OmegaPhil@startmail.com)
